//Login request action
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

//Transport list action
export const TRANSLIST_REQUEST = 'TRANSLIST_REQUEST';
export const TRANSLIST_REQUEST_SUCCESS = 'TRANSLIST_REQUEST_SUCCESS';
export const TRANSLIST_REQUEST_FAILURE = 'TRANSLIST_REQUEST_FAILURE';

//Add Transport Request 
export const ADDTRANS_REQUEST = 'ADDTRANS_REQUEST';
export const ADDTRANS_REQUEST_SUCCESS = 'ADDTRANS_REQUEST_SUCCESS';
export const ADDTRANS_REQUEST_FAILURE = 'ADDTRANS_REQUEST_FAILURE';

//Transport delete action
export const DELETETRANS_REQUEST = 'DELETETRANS_REQUEST';
export const DELETETRANS_REQUEST_FAILURE = 'DELETETRANS_REQUEST_FAILURE';
export const DELETETRANS_REQUEST_SUCCESS = 'DELETETRANS_REQUEST_SUCCESS';

//Transport Update action
export const UPDATETRANS_REQUEST = 'UPDATETRANS_REQUEST';
export const UPDATETRANS_REQUEST_SUCCESS = 'UPDATETRANS_REQUEST_SUCCESS';
export const UPDATETRANS_REQUEST_FAILURE = 'UPDATETRANS_REQUEST_FAILURE';




